# Conclusion

In 5, visualization and analysis of company data was done in various manners.
Company has its strength in its capital power where company has been operated
conservatively, while keep good equity to debt ratio. Furthermore, since manufacturing
and construction business are regarded as "Steady" business sector, There will be less
room for company to drastically decrease in its sales(and profit).
However, steel and manufacturing business has become red ocean and competition between
steel companies has become intense. 
Moreover, due to the nature of steel business, it is heavily rely on the price of mineral. 
Construction business is also operated based on bidding, so portfolio management and R&D is crucial.
In terms of opportunity, Since 72.1 % of Korea consists of mountainous district, there will be
further expansion in clearing mountain. Growth in population would be a factor for active city construction as well.
I believe construction business will play major role in this process. 
Though it is impossible to predict accurately when it will happen, but if union of North Korea and
South Korea comes true, both steel and construction business will be booming.


To conclude, I believe company should focus on finding future business and invest more on high-profitable business to have
competency in future. But at the same time, company has to put effort on maintaining its market capitalization in both steel and construction business.